"""Add task fields

Revision ID: 27446b232f8c
Revises: c549a5c0f5a5
Create Date: 2025-06-04 10:15:30.658740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27446b232f8c'
down_revision = 'c549a5c0f5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
